### PR TITLE
Update template.pot, ja.po

### PR DESCRIPTION
**Pull request by scrwnl**

### CODE REVIEW

**Comment by seagetch** [comment]
I'll check it later at night.
Basically good.
Some expression might be better to add minor modification.

**Comment by seagetch** [comment]
Several minor comments:
- "%s locked to root node" might be better to translate as "%sがルートノードに固定されました", because it is description of redo/undo, and describes action. 
- Same for "%s unlocked from root node."
- "Merges (adds) selected image files to project" might be better to translate as "選択されている画像をプロジェクトにマージ(追加)します。" to make consistency with other translations.

Others seems good.

**Comment by seagetch** [comment]
For last comment, I note some convention of translation I applied.
I used "です/ます" style for tool tip text, and "である" style for menu text. 
Maybe this is typical in many software.
Text above is description of tooltip, so using "です/ます" is preferred.

**Comment by scrwnl** [comment]
I fixed that parts.
Thank you for your some appropriate advice.
I7m sorry for my late reply.


Incidentally, should I put the long vowel symbol at the end or not? (e.g. サーバー, サーバ)

**Comment by seagetch** [comment]
LGTM.

> Incidentally, should I put the long vowel symbol at the end of word or not? (e.g. サーバー, サーバ)
Good question.
I think either is okay as long as we keep unified notation. Many engineers prefer サーバ/ユーザ for historical convention, but newer rule recommends サーバー/ユーザー (Microsoft changed their text to newer rule.)
[「サーバー」と「サーバ」、どっちが正解? - 【ビジネス用語】](https://news.mynavi.jp/article/20180419-617682/)

At a glance, Current translation is unintentionally mixed both.
Texture --> currently "テクスチャ", should be "テクスチャー"
Accessibility --> currently "アクセシビリティ", should be "アクセシビリティー"
Parameter --> currently "パラメータ", should be "パラメーター"
Folder --> currently "フォルダ", should be "フォルダー"
Property --> currently "プロパティ", should be "プロパティー"
etc.

**Comment by seagetch** [comment]
@scrwnl if you finished all of you translation work, it might be good to ask @LunaTheFoxgirl to merge this.

**Comment by LunaTheFoxgirl** [comment]
Yeah I'm just waiting for you two to tell me that it's ready to merge

**Comment by seagetch** [comment]
I think it's a good time to merge this once.

**Pull request merged**
